### ISSUE TITLE
Error when training process ModuleNotFoundError: No module named 'mmdet'

### ISSUE THREAD

**Issue by neni1705** [FishYuLi/BalancedGroupSoftmax#17]
(mmdet) D:\BalancedGroupSoftmax>python tools/train.py configs/bags/gs_faster_rcnn_r50_fpn_1x_lvis_with0_bg8.py
Traceback (most recent call last):
  File "tools/train.py", line 8, in <module>
    from mmdet import __version__
ModuleNotFoundError: No module named 'mmdet'

I got this error when I did the training, is there something wrong? I am looking forward for your repply

**Comment by Taoxianer** [comment]
请问你解决了吗，我也遇到了，应该怎么去解决呢

**Comment by neni1705** [comment]
I can't solve it.
