### ISSUE TITLE
A simple question regarding design choice of BAGS

### ISSUE THREAD

**Issue by hdjang** [FishYuLi/BalancedGroupSoftmax#3]
Hi
Thanks for sharing your wonderful project.

I have a simple question regarding design choice of BAGS. It would be appreciated if you would answer. 

Q) Why didn't you try normalizing weight norm of classifier instead of grouping the category in the paper? Have you ever tested it before?

**Comment by FishYuLi** [comment]
@hdjang Thanks for the good words.

(1) We tried to normalize weights after training following [t-norm](https://arxiv.org/pdf/1910.09217.pdf), the results of which are presented as Model(12)(13) in both our paper and README. The details are in [supp](https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Li_Overcoming_Classifier_Imbalance_CVPR_2020_supplemental.pdf) 1.2.t-normalization. Though we tried many ways to do this normalization, the results are not very good yet. 
(2) However, we haven't tried to use weight normalization during training. And we are now working on it :) .
